### ISSUE TITLE
Make some ExtensionMethods public for ICustomRule

### ISSUE THREAD

**Issue by cmenzi** [NeVeSpl/NetArchTest.eNhancedEdition#6]
Hi

I like this project very much, but currently it's a bit hard to write custom rules, because some of the extension methods, like TypeReferenceExtensions, TypeDefinitionExtensions, ... are internal.

For example, I like to write a CustomRule that checks if there are at least 3 TraitAttributes applied to all classes inherited from IntegrationTestBase.

Currently, I can only check against name or fullname of the attribute, because I cannot easily create a TypeDefinition or TypeReference from `typeof(TraitAttribute)`. 

I saw, there would be a `ToTypeDefinition()` method. Having this, would make it really handy.

And maybe 2nd question. How can I add a `Explanation` to custom Rules? Currently, there is only a `bool` as return value.

**Comment by NeVeSpl** [comment]
What about going in the opposite direction and making `Type TypeDefinitionExtensions.ToType(this TypeDefinition typeDefinition)` public? Would not be that enough? 

I would rather prefer to embrace end-user to use reflection API, instead of Mono.Cecil API which should be an implementation detail hidden from the end-user, but unfortunately this is a way that the original library has taken. 

Regarding the second question, it is not possible in the current API, but it is fully supported internally, so the only question is how to expose that through API.

**Comment by cmenzi** [comment]
> What about going in the opposite direction and making `Type TypeDefinitionExtensions.ToType(this TypeDefinition typeDefinition)` public? Would not be that enough?
> 
> I would rather prefer to embrace end-user to use reflection API, instead of Mono.Cecil API which should be an implementation detail hidden from the end-user, but unfortunately this is a way that the original library has taken.

Sure, I can live with that as well and was initially what I've been looking for. :-)
 
> Regarding the second question, it is not possible in the current API, but it is fully supported internally, so the only question is how to expose that through API.

I guess, `ICustomRule` would need to be anyway redesigned, so that it does not have a visible Mono.Cecil dependency. 

I would expect something like a `CustomRuleResult`. 

`return new CustomRuleResult(success: true, explanation: "Because of this and that`

or

`return CustomRuleResult.Success()` and `CustomRuleResult.Failed("Because of this and that")`

But encapsulating all of stuff 'Mono.Cecil` or TypeDefinition and TypeReference would be a lot of work, I guess.
